name: Deploy Static App

on:
  push:
    branches:
      - 'main'

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - run: 'pnpm build'
        env:
          KIT_ADAPTER: static
          VITE_API_URL: https://si21.herokuapp.com
          BASE_PATH: /${{ github.event.repository.name }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
